### ISSUE TITLE
Demo doesn't work in Chrome stable

### ISSUE THREAD

**Issue by borismus** [mrspeaker/worldt#2]
Got the following errors:

Failed to load resource: the server responded with a status of 404 (Not Found)
mrspeaker.github.io/:1 XMLHttpRequest cannot load https://jspm.io/babel.js. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://mrspeaker.github.io' is therefore not allowed access. The response had HTTP status code 404.
es6-module-loader@0.14.0.src.js:140Potentially unhandled rejection [5] Error loading "src/main" at http://mrspeaker.github.io/InternetExplorer/src/main.js
Error loading "@babel" at https://jspm.io/babel.js
: https://jspm.io/babel.js (WARNING: non-Error used)

ps. thanks for using the polyfill :)

**Comment by mrspeaker** [comment]
Thanks for the report - looking into this now.

**Comment by mrspeaker** [comment]
I've moved back to npm/babel - so I think this shouldn't be an issue now.
